# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZilQosGAcxmONqU54z4BJZCgULJVz7O
"""

!pip install gradio

from transformers import pipeline
import gradio as gr
from PIL import Image
image_path = "image.png"
pipe = pipeline("image-segmentation", model="briaai/RMBG-1.4", trust_remote_code=True)
pillow_mask = pipe(image_path, return_mask = True) # outputs a pillow mask
pillow_image = pipe(image_path) # applies mask on input and returns a pillow image

pillow_mask

pillow_image

image_path = 'https://cdn3.gnarususercontent.com.br/3975-hugging-face-modelos-ia/Projeto/Aula%203%20-%20Imagens/camera_fotografica.jpg'
pipe = pipeline("image-segmentation", model="briaai/RMBG-1.4", trust_remote_code=True)
pillow_mask = pipe(image_path, return_mask = True) # outputs a pillow mask
pillow_image = pipe(image_path) # applies mask on input and returns a pillow image

pillow_mask

pillow_image

def remove_background(img):
  pipe = pipeline('image-segmentation', model='briaai/RMBG-1.4', trust_remote_code=True)
  pillow_mask = pipe(img, return_mask=True)
  pillow_image = pipe(img)

  return pillow_image

app = gr.Interface(
    fn=remove_background,
    inputs=gr.components.Image(type='pil'),
    outputs=gr.components.Image(type='pil', format='png'),
    title='Remoção de Background de Imagens',
    description='Envie uma imagem para remover seu backgroud automáticamente. SAIDA EM PNG.'
)

app.launch(share=True)

